### PR TITLE
LPS-194320

### PR DESCRIPTION
**Pull request by danielCamara02**
https://liferay.atlassian.net/browse/LPS-194320

### CODE REVIEW

**Comment by danielCamara02** [comment]
ci:test:sf

**Comment by danielCamara02** [comment]
ci:test:search

**Comment by danielCamara02** [comment]
ci:test:sf

**Comment by danielCamara02** [comment]
ci:test:search

**Comment by danielCamara02** [comment]
ci:test:sf

**Comment by danielCamara02** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:forward

**Pull request closed without merging**
